### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by PhoenixRight** [objection-lol/website#105]
Hello, dear developers!
I suggest replacing pixel character icons with HD icons:
![Pixel icons](https://user-images.githubusercontent.com/73066569/99958068-57b63980-2d91-11eb-831f-c81e385cd59b.png)
![HD icons](https://user-images.githubusercontent.com/73066569/100007706-1f384f00-2dd5-11eb-8177-9fd8d3a21ca0.png)

<details>
<summary>icons</summary>

![Phoenix](https://user-images.githubusercontent.com/73066569/99958119-79afbc00-2d91-11eb-8b7a-4e04444083e6.png)
![Edgeworth](https://user-images.githubusercontent.com/73066569/99958166-8df3b900-2d91-11eb-853b-f347542ed34a.png)
![Edgeworth (young](https://user-images.githubusercontent.com/73066569/99958185-98ae4e00-2d91-11eb-98d3-ad85c56443e2.png)
![Mia](https://user-images.githubusercontent.com/73066569/99958231-afed3b80-2d91-11eb-9aba-606b7f7ce7b3.png)
![Armando](https://user-images.githubusercontent.com/73066569/99958275-c1364800-2d91-11eb-9153-c5c71f02cdba.png)
![Payne](https://user-images.githubusercontent.com/73066569/99958294-cd220a00-2d91-11eb-915c-05b4c83bb7c1.png)
![von Karma](https://user-images.githubusercontent.com/73066569/99958318-d90dcc00-2d91-11eb-907b-d175cb7474e3.png)
![Karma](https://user-images.githubusercontent.com/73066569/99958374-f93d8b00-2d91-11eb-825a-d8fb2f160b72.png)
![Godot](https://user-images.githubusercontent.com/73066569/99958419-06f31080-2d92-11eb-905d-f9af724ee11f.png)
![Judge](https://user-images.githubusercontent.com/73066569/99958510-2722cf80-2d92-11eb-9785-ea1be057be68.png)
![Apollo](https://user-images.githubusercontent.com/73066569/99958533-34d85500-2d92-11eb-96ab-540155bd1e8f.png)
![Klavier](https://user-images.githubusercontent.com/73066569/99958559-44579e00-2d92-11eb-82a7-031ea2b4879b.png)

**Comment by objection-lol** [comment]
Thanks for the suggestion, we are using the older icons because they are smaller in size and still let you know which character it is, in Courtroom there are 100 icons so the file size of the icons matters there.
