### ISSUE TITLE
Icons of Assets and Objections 

### ISSUE THREAD

**Issue by Mutsuyoshi** [objection-lol/website#117]
Is it me, or should it be the other way around? 
![Screenshot_20201125_174110](https://user-images.githubusercontent.com/74418423/100242234-a3a9df80-2f45-11eb-8613-4ca03f7b2b02.jpg)

**Comment by Mutsuyoshi** [comment]
Nah Gebrochenes Englisch

**Comment by 21memes21** [comment]
I mean if the buttons do what they are supposed to do i don't see why it should be changed?

**Comment by Mutsuyoshi** [comment]
"Camera" for Objections, "file" for assets

**Comment by objection-lol** [comment]
Fixed.
