### ISSUE TITLE
[Feature] Ability to string multiple objections together

### ISSUE THREAD

**Issue by resindrake** [objection-lol/website#127]
Being able to string objections together form a full trial made of multiple court sessions, as well as things like interviews, visits to the crime scene, etc, each as separate objections, could make the editing process a lot easier for full turnabouts

**Comment by objection-lol** [comment]
Although not ideal, you can do something like this:
![image](https://user-images.githubusercontent.com/71948517/101061896-0e8c9380-35a2-11eb-95d7-2805a997c9bd.png)

**Comment by resindrake** [comment]
I guess that does work to some degree, although the objections in my case would be completely out of order as I didn't make them chronologically
