### ISSUE TITLE
A "DS Mode"

### ISSUE THREAD

**Issue by 21memes21** [objection-lol/website#135]
It would be cool to have the ability to have a "ds mode" where all sprites,backrounds,speech bubles and sounds are downgraded back to their ds versions.

**Comment by Audacity0001** [comment]
I like this suggestion, +1.

**Comment by objection-lol** [comment]
Hey.
Thanks for the suggestion. You can add the DS sprites as custom characters, including the speech bubbles, but they won't be available as preset characters.

**Comment by 21memes21** [comment]
about the sounds (for example desk slam),we don't have the ability to change them to sound more like its from the ds

**Comment by TalesSouzones** [comment]
yeah cool

Em seg., 7 de dez. de 2020 às 10:54, 21memes21 <notifications@github.com>
escreveu:

**Comment by objection-lol** [comment]
> about the sounds (for example desk slam),we don't have the ability to change them to sound more like its from the ds

You can in custom characters.

**Comment by 21memes21** [comment]
> > about the sounds (for example desk slam),we don't have the ability to change them to sound more like its from the ds
> 
> You can in custom characters.

i see,thanks for the clarification
