### ISSUE TITLE
16:9 backgrounds

### ISSUE THREAD

**Issue by Luciferchick** [objection-lol/website#151]
Make the background full screen, without black stripes on the sides.

**Comment by sunkhaskasis** [comment]
I'm afraid that'd cause a lot of inconsistencies. While it is true that the AA Trilogy backgrounds are fit for widescreen, a lot of AJ ones aren't since they're made to fit the resolution of a mobile device.

**Comment by objection-lol** [comment]
We're also using the mobile Trilogy character sprites, that's why the resolution in the website is weird (960x640) or 3:2 aspect ratio.
If one day we get The PC game sprites we can change to 16:9.

**Comment by Mutsuyoshi** [comment]
> We're also using the mobile Trilogy character sprites, that's why the resolution in the website is weird (960x640) or 3:2 aspect ratio.
> If one day we get The PC game sprites we can change to 16:9.

I will find this maybe. Last day i got not enough time, cause of SFA (Basic State Examination)

**Comment by objection-lol** [comment]
> > We're also using the mobile Trilogy character sprites, that's why the resolution in the website is weird (960x640) or 3:2 aspect ratio.
> > If one day we get The PC game sprites we can change to 16:9.
> 
> I will find this maybe. Last day i got not enough time, cause of SFA (Basic State Examination)

I don't mean the spritesheets, I know they exist, I mean to have the characters animated as gif images.

**Comment by objection-lol** [comment]
Closed as stale.
