### ISSUE TITLE
New line / carriage return?

### ISSUE THREAD

**Issue by KitsuneKimmy** [objection-lol/website#154]
I've been looking through everything on the site, and I admit I don't see a way to add a carriage return / new line to a line of text in a single frame so that I can format certain text to look more like the game for certain scenes. Is that something I'm just missing? I'm hoping to use it to parse dialog as well as format things like the time/date/location popups that happen on certain scene transitions in the games. Thank you!

**Comment by objection-lol** [comment]
Its not possible to do that, not right now at least, sorry.
