### ISSUE TITLE
Evidence icon when no character on screen?

### ISSUE THREAD

**Issue by KitsuneKimmy** [objection-lol/website#155]
For some reason, when I want to display evidence and there's no character on the screen (i.e. an empty witness stand) the evidence icon doesn't show up at all. The only workaround I've found is to force the background to be the witness stand, set the character to "Gallery", set that to an empty crowd, and manually hide all NPCs in the gallery since they seem to pop up. Is there some other way to have an empty witness stand and have an evidence icon show up?

**Comment by objection-lol** [comment]
Fixed.
