### ISSUE TITLE
Evidences and your own musics

### ISSUE THREAD

**Issue by LordFawful** [objection-lol/website#158]
I has a suggestion for adds photos and your own musics in objection.lol. With the links, adds evidences is very annoying. But it's only 50% of problem. Your own music and sound effects is almost impossible to add. So i have suggestion, adds photos from galery and your music from music app. I hope you will do it.
Example how does this can be look:![PicsArt_12-13-12.37.48.jpg](https://user-images.githubusercontent.com/74718198/102005009-e6d6c180-3d3f-11eb-8ee4-9cd05eb516e2.jpg) and also sorry for my terrible english, i'm russian

**Comment by objection-lol** [comment]
Hi,
I know uploading file directly from your device is better, but we don't have a big server to do that.
Also in next update the preview of evidence will not show anymore, making it slightly less annoying.
