### ISSUE TITLE
Custom Characters Can't Use Existing Backgrounds

### ISSUE THREAD

**Issue by Peekofwar** [objection-lol/website#162]
I noticed when I went to create a custom character, I was not allowed to simply set the background to the Phoenix Wright witness stand background. I had to upload the image somewhere and attach it as a custom background instead. 

I feel like we should be allowed to use existing backgrounds instead of being limited to custom backgrounds.

**Comment by LordFawful** [comment]
I don't know why, but i didn't has that glitch ._.

**Comment by Peekofwar** [comment]
> I don't know why, but i didn't has that glitch ._.

Hrm... They may have already fixed it then...

**Comment by Peekofwar** [comment]
> I don't know why, but i didn't has that glitch ._.

Hrm... They may have already fixed it then...
