### ISSUE TITLE
Character blip doesn't work on Firefox

### ISSUE THREAD

**Issue by HazmatDrone** [objection-lol/website#167]
Firefox Version 83.0 on Manjaro Linux
##### Sounds that don't work:
- Character text blips
- ~~Custom music~~

**Comment by objection-lol** [comment]
I just tried and it works, make sure the links aren't broken (e.g. custom music url)
Tried this one: [#bgm11916]

**Comment by HazmatDrone** [comment]
The links aren't broken; when editing in Chrome I have no issues with this.
I get no music for [this](https://objection.lol/objection/770623) objection in Firefox, but in Chrome, it's fine

**Comment by HazmatDrone** [comment]
I tested the custom music in a fresh installation of Firefox and the music worked, so it might just be getting blocked by one of my privacy addons. I'll try and figure out details and send them here.

However, the character blips were still broken

**Comment by HazmatDrone** [comment]
Testing reveals that the music (added via Discord URL) was being blocked by Privacy Badger. I'll open a discussion about this for other users to be aware of.

**Comment by objection-lol** [comment]
That's strange, its working for me.
Is it because you're not on a Windows PC?

**Comment by HazmatDrone** [comment]
It could play a part, perhaps. Here's the console output; it might help.
```
Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:29:486
Cookie “_gid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:29:486
Cookie “_gat” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by objection-lol** [comment]
Yes, that's from Google Analytics.

**Comment by HazmatDrone** [comment]
Testing on a Windows PC, it does in fact work. And looking through the network debugger, I can confirm that the file blip.wav is downloaded when the site loads. It might just be an issue with .wav files on this machine. I'll look into this further.

**Comment by HazmatDrone** [comment]
Yeah, I have a gut feeling that my machine is just unable to play .wav files for some reason; .mp3, .ogg, etc, all seem to play just fine. I had some other Manjaro users test this and they seem to have no issues.
