### ISSUE TITLE
Freezing when no character is used

### ISSUE THREAD

**Issue by MelonWaterMelon** [objection-lol/website#210]
Hi! I've been having an issue where I want to show a background with a textbox but without a character. When I select 'None' under the character options, though, the program usually refuses to play the slide. It worked at first, but later, without me changing anything, the slide stopped playing-- previewing only gave a black screen. Is it possible to show a background with text but without a character? If selecting the 'Gallery' character is required, how can I hide the character sprites that appear? 

Thanks a bunch!

**Comment by objection-lol** [comment]
Hi,
You don't need to select Gallery, just select "None" as character and set any background. Check if the background URL is still valid, maybe the background link has become broken, you can edit your custom background and replace the link.

**Comment by MelonWaterMelon** [comment]
> Hi,
> You don't need to select Gallery, just select "None" as character and set any background. Check if the background URL is still valid, maybe the background link has become broken, you can edit your custom background and replace the link.

I'm actually using one of the preexisting backgrounds, the Von Karma one specifically (although I don't think the background I chose has any bearing on the issue). When I choose "None", regardless of if I have a custom name or toggle the 'No Talking' switch, the slide won't play. So sorry for the inconvenience!

**Comment by objection-lol** [comment]
It was a bug and it has been fixed, thanks.

**Comment by MelonWaterMelon** [comment]
> It was a bug and it has been fixed, thanks.

Thank you so much! :D
