### ISSUE TITLE
Issues, suggestions and important remarks!

### ISSUE THREAD

**Issue by TailsDoll-OS** [objection-lol/website#36]
Good afternoon.
I have got multiple requests to you as a user of objection.lol's (especially concerning the courtroom)
1. There are some missing features **in the courtroom** :
- There are no longer **pause** features, 
- neither I can't use a full RGB panel like before, nor I can assign colors. It was replaced by a mere color line.[**both objection maker and courtroom**]
- the color itself applies only to the whole text, but I used to attach the colors to certain words (with tags).
- I also can't change the speed of the text like before.

2. I want to suggest you remaking Apollo Justice characters by using 3ds sprites.

Also, there is a list of all missing characters (in my opinion):

Phoenix Wright: Ace Attorney:
- Penny Nichols

[...]Justice For All:
- Ben & Trilo
- Wendy Oldbag (JFA version)
- Will Powers (tuxedo)

[...]Trials and Tribulations:
- Terry Fawles
- Larry Butz (as Laurice Deauxnim)
- Sister Bikini
- Dick gumshoe (Young)
**- Also Godot had bleeding eyes sprites as well.**

Apollo Justice: Ace Attorney:
- Drew Misham
- Zak Gramarye (Shadi Enigmar)
- Valant Gramarye
- Lamiroir
- Spark Brushel
- Klavier Gavin (young)
- Olga Orly
- Wesley Stickler
- Wocky Kitaki
- Alita Talia
- Machi Tobaye
- Daryan Crescend

There were also the **Hotline of fate** and **Thrill theme** tracks missing. In my opinion they have to be in your music list as the most thrilling suspense/fate themes.

3. There are also some suggestions about the effects
- Assigning characters in the gallery before the objection or courtroom starts
- smooth light
- removing the character (showing only a stand without any character, for example as if he felt down)
- Change of the backgrounds (including black one and ability to insert big sprites with it)

That's all from me. My apologies if this is too much from me.

**Comment by TailsDoll-OS** [comment]
Also, sorry if it is too much, but can I also ask you to make something "like locations"? Like for example tho different courtroom designs:
1. Phoenix Wright courtroom (the current one)
2. Apollo justice courtroom (as a sort of redesign)

P.S. I'd be happy to see the ability to have access to the defendant's lobbies.
And I'd like to be able to type the green text in the center as well as the game writes the location and time.

**Comment by TailsDoll-OS** [comment]
Edit 2:
I really would be happy if the features in the courtroom returned: pauses, color tags, text speed tags, **(especially) RGB panel**. I'm sorry if it seems to be a bit annoying, but I hope you see it and return those amazing features.

**Comment by objection-lol** [comment]
Hey.
The color and text speed in the courtroom automatically affect the entire message, it was made like that just so its easier to use, however, it's still possible to use the tags like in the Maker page, if you copy-paste this it will work in the courtroom:
This is [#/r]red[/#]

If you're looking for using the record function to make your objection, you can edit the frames after you download them.

**Comment by TailsDoll-OS** [comment]
Thank you, but I think I got four more ideas:
1. Can you make "expand" button so the user could use both simple and RGB variants?
2. You also can make two buttons "apply to the whole text" and "insert tag"
3. Gavel animations in courtroom.
4. And how about making "Guilty" and "Not Guilty" labels?

I appreciate your effort and as I said, I look forward to seeing your website in its full beauty!

**Comment by TailsDoll-OS** [comment]
P.S. I've forgotten to mention adding Hotline of Fate, it's one of my favorite soundtracks

**Comment by objection-lol** [comment]
> P.S. I've forgotten to mention adding Hotline of Fate, it's one of my favorite soundtracks to be honest.

It's possible to add your own tracks, here's an example:
- Use https://ytmp3.cc/en13/ to get MP3 off a YouTube video like https://www.youtube.com/watch?v=fUI9Pw2wfZU
- Upload the MP3 to Discord or somewhere that supports hotlinking (e.g. FTP space)
- Copy the link to the Custom Music URL field.

**Comment by TailsDoll-OS** [comment]
I don't think it would sound great as mp3:
1. The theme itself has an entry and loop, the first one is played once, the second gets in a loop, just like the "cornered" theme, same for the "Thrill theme". If you upload it as mp3, both parts will be looped, so it won't sound as good as in the game
2. I cannot upload the extended version as well, since the website has limits of uploaded music. This limit would do good with SFX, but not with soundtracks.

**Comment by objection-lol** [comment]
It seems we can remove the limit on music size, as it won't even download the whole track, it downloads as it goes like a YouTube video. Thank you this has been noted.

**Comment by TailsDoll-OS** [comment]
Good afternoon.
I've got another suggestion. Could you divide the soundtracks so that we knew which game it appears from and/or correct their names? 
There are lists of Ace Attorney OSTs, I hope it will help.

Ace Attorney 1-3 (Trilogy) + Apollo Justice + Ace Attorney Investigations
[https://www.youtube.com/playlist?list=PL661F534D5EB64093](url) 

Ace Attorney Investigations 2:
[https://www.youtube.com/playlist?list=PL3EDBB8487C9EB794](url)
 
P.S.: You could as well add abbreviations for the tracks before their titles, like "PW1", "PW2", "PW3", "AJ", "AAI1", "AAI2", so they'd be in some kind of groups.
I'm looking forward to your best updates. 👍

**Comment by objection-lol** [comment]
Thanks for the compilation.
Most of these have been done, closing as its been open for a long time, please make a new issue if needed.
