### ISSUE TITLE
[Suggestion] Option for Roleplaying Courtroom

### ISSUE THREAD

**Issue by rendemletters** [objection-lol/website#71]
An option while creating a Courtroom lobby to make it a roleplay lobby. This will restrict users to only one character that they will have to choose while joining.

Love your work!!

**Comment by rendemletters** [comment]
Also I know I'm asking a lot but is it possible to make a desktop client for the Courtroom? The biggest problem right now is that it takes time to load especially if you're new to the lobby and that takes away the fun

**Comment by objection-lol** [comment]
Thank you, it will be considered.

**Comment by objection-lol** [comment]
You can disable custom characters if you are the owner the courtroom.
Additionally, restricting to 1 character is not possible, people can just refresh the page and select a different character.
For mobile courtroom app, it may be done or maybe not.
