### ISSUE TITLE
Hide character option

### ISSUE THREAD

**Issue by Cl0ckHvH** [objection-lol/website#79]
It would be cool to hide characters in the selectable menu. Why? Because it's not comfortable to scroll up and down to select a character. I know about search, but it's not working on mobiles

**Comment by Cl0ckHvH** [comment]
Or make tab for characters, that you can add to this custom tab

**Comment by objection-lol** [comment]
We can enable the search on mobile, but I don't think you'd be happy to see the on-screen keyboard show up every time you want to change the character, adding filters is a good idea.

**Comment by maxdevgithub** [comment]
I automatically thought of fading in/out characters

**Comment by objection-lol** [comment]
A filter has been added.
